language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-playground' ]; then cd .. && eval "mv $currentfolder generator-playground" && cd generator-playground; fi

